n_games=int(input("Enter Number of games in tournament= "))
n_lost=int(input("Enter number of games lost= "))
n_won=int(input("Enter number of games won= "))
n_ties=n_games-(n_lost-n_won)
print(f"Number of games got tie {n_ties}")
total_point=(4*n_won)+(2*n_ties)
print(f"Total Points {total_point}")