a='delhi is a clean clean city'

#print(a.lower())
#print(a.upper())
#print(a.title()) #First letter of every word is captialized
#print(a.capitalize()) #Frist letter of the string is captialized
#print(a.swapcase()) #change case of each and every character
#print(a.islower()) #Returns boolean True if complete string is are lower,it ignores numbers and symbols
#print(a.isupper()) #Returns boolean True if complete string is are lower,it ignores numbers and symbols
#print(a.isalpha()) #Returns boolean True if complete string is alphabet , this will show false since there is a space
#print(a.isalnum)  #Reurns boolean True checks alphates or numbers this will show false since there is a space
#print(a.isdigit)  #Reurns boolean True checks if are numbers in the string 
#print(a.replace("i","z")) #replaxe all i in the string to z
#print(a.index("c")) #shows the index of first c in the input string
#print(a.index("de")) #will show index of d
#print(a.find("p")) #find is same as index however if the letter is not present index gives error and find returns -1
#print(a.rfind("e")) #finds the letter starting from right
# sample='   abc yz x   '
# print(sample.strip()) #reomves white spaces(tab enter space etc) from left and right and also \n
# print(sample.rstrip()) #remove right white spaces
# print(sample.lstrip()) #remove right white spaces
# print(sample.strip('@')) #its not there so wont remove
# sample='@ @@@@@   abc yz x'
# print(sample.strip('@')) #will remove only 1st @ since it found space after tha





